---
layout: post
title: Feet Fueled Rockets
date: 2013-06-17 01:37:49.000000000 -07:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories: []
tags: []
meta:
  _publicize_pending: '1'
author:
  login: bzreinhardt
  email: bzreinhardt@gmail.com
  display_name: Ben
  first_name: Ben
  last_name: Reinhardt
---
<p>A tale of incentives and innovation generated by post-travel-pre-Ames rushing:</p>
<p> Today I got a bike from <a href="http://www.yelp.com/biz/rent-my-bike-stanford">a startup</a> that rents out bikes that need a home over the summer. It’s inefficiency destroying and thus full of win:</p>
<ul>
<li> I win because I get a nice bike for the summer with all accessories for much less money and time than it would cost to ship a bike.</li>
<li>The company wins because they make money.</li>
<li>The students <b>giving</b> the bikes win because apparently you’re not allowed to store your bikes on campus without a large fee.  Notice that even here, events are driven by government incentives (for all intents and purposes, the school is the government on campus.)</li>
</ul>
<p> The player that loses? The campus bike shop that rents bikes for more than twice as much.</p>
<p>What does this have to do with space?</p>
<p> Imagine if Stanford needed to certify each bike rented out, to make sure it wouldn’t hurt the rider or something clearly absurd with respect to bicycles. This whole operation probably wouldn’t be able to exist, and nobody would reap any benefits, except for the campus bike shop (who in our fiction probably incentivized the administration to pass the ordinance.) Instead, we would be stuck with only the more expensive (though not necessarily better) bikes provided by the government sanctioned entity and thus fewer people would be able to reap their benefits.</p>
<p> See where this is going?  [hint: it involves replacing ‘bicycle’ with ‘space tech.’]</p>
<p> The upshot is, not to be too preachy, that one of the best things the government can do for space flight is just to stay out of the way so that incentives can cause the world (and beyond!) to become more full of win. </p>
